### ISSUE TITLE
「The schema and path do not exist: metadata.json」エラー発生

### ISSUE THREAD

**Issue by henami** [nims-dpfc/rdetoolkit#11]
担当者様

いつもありがとうございます。

RDEToolKit 0.1.10を想定して作成したソースを、0.9.0に合わせて修正しました。
```
1) ModuleNotFoundError: No module named 'rdetoolkit.invoiceFile'

modules/invoice_handler.py

-from rdetoolkit.invoiceFile import InvoiceFile
+from rdetoolkit.invoicefile import InvoiceFile

2) AttributeError: 'Meta' object has no attribute 'assignVals'

modules/datasets_process.py

-    metaobj.assignVals(metaDict)
+    metaobj.assign_vals(metaDict)

3) AttributeError: 'Meta' object has no attribute 'writeFile'

modules/datasets_process.py

-    metaobj.writeFile(save_path)
+    metaobj.writefile(save_path)
```

これで、想定していた部分は動いたと思いますが、最後にエラーになります。これは私がコーディングした部分を通った後に何かが起こったように見えます。

```
(pymatgen+rde) $ python main.py
：
Traceback (most recent call last):
  File "/home/enami/pymatgen+rde/lib/python3.11/site-packages/rdetoolkit/workflows.py", line 200, in run
    invoice_mode_process(srcpaths, rdeoutput_resource, custom_dataset_function, config=__config)
  File "/home/enami/pymatgen+rde/lib/python3.11/site-packages/rdetoolkit/modeproc.py", line 289, in invoice_mode_process
    metadata_validate(resource_paths.meta.joinpath("metadata.json"))
  File "/home/enami/pymatgen+rde/lib/python3.11/site-packages/rdetoolkit/validation.py", line 77, in metadata_validate
    raise FileNotFoundError(emsg)
FileNotFoundError: The schema and path do not exist: metadata.json
```

肝心のmetadata.jsonですが、
```
(pymatgen+rde) $ tree data/meta
data/meta
└── matadata.json

1 directory, 1 file
```
という感じで、想定の位置にmetadata.jsonを配置したつもりです。なにがいけないのでしょうか?

よろしくお願いします。

**Comment by henami** [comment]
すみません、自己解決しました。

```
modules/datasets_process.py

-    save_path = resource_paths.meta / "matadata.json"
+    save_path = resource_paths.meta / "metadata.json"
```

はずかしいタイポでした。お騒がせしました。修正後問題なく稼働することを確認しました。

**Comment by henami** [comment]
状況を整理します。

* RDEToolKit 0.9.0をインストール
* 適当にディレクトリを作成し、init処理実行
* containerディレクトリに移動して、そのまま"python main.py"を実行

これで、"FileNotFoundError: The schema and path do not exist: metadata.json"がでます。

このとき、たしかにdata/metaの下には何もありません。
```
(tenv) $ python main.py
Traceback (most recent call last):
  File "/home/devel/tenv/lib/python3.11/site-packages/rdetoolkit/workflows.py", line 200, in run
    invoice_mode_process(srcpaths, rdeoutput_resource, custom_dataset_function, config=__config)
  File "/home/devel/tenv/lib/python3.11/site-packages/rdetoolkit/modeproc.py", line 289, in invoice_mode_process
    metadata_validate(resource_paths.meta.joinpath("metadata.json"))
  File "/home/devel/tenv/lib/python3.11/site-packages/rdetoolkit/validation.py", line 77, in metadata_validate
    raise FileNotFoundError(emsg)
FileNotFoundError: The schema and path do not exist: metadata.json
(tenv) $ tree
.
├── Dockerfile
├── data
│   ├── inputdata
│   ├── invoice
│   │   └── invoice.json
│   ├── job.failed
│   ├── logs
│   │   └── rdesys.log
│   ├── main_image
│   ├── meta
│   ├── nonshared_raw
│   ├── other_image
│   ├── raw
│   ├── structured
│   ├── tasksupport
│   │   ├── invoice.schema.json
│   │   └── metadata-def.json
│   ├── temp
│   └── thumbnail
├── main.py
├── modules
└── requirements.txt

15 directories, 8 files
```

上のtypoは置いておいて、この何もしない状態での実行時エラーを出なくして欲しいです。

※なお、開発版でやっても同じでした。
```
(tenv) $ python main.py
Traceback (most recent call last):
  File "/home/devel/tenv/lib/python3.11/site-packages/rdetoolkit/workflows.py", line 227, in run
    invoice_mode_process(srcpaths, rdeoutput_resource, custom_dataset_function, config=__config)
  File "/home/devel/tenv/lib/python3.11/site-packages/rdetoolkit/modeproc.py", line 289, in invoice_mode_process
    metadata_validate(resource_paths.meta.joinpath("metadata.json"))
  File "/home/devel/tenv/lib/python3.11/site-packages/rdetoolkit/validation.py", line 77, in metadata_validate
    raise FileNotFoundError(emsg)
FileNotFoundError: The schema and path do not exist: metadata.json


============================================================
Custom Traceback (simplified and more readable):
============================================================

Traceback (simplified message):
Call Path:
   File: /home/devel/tenv/lib/python3.11/site-packages/rdetoolkit/workflows.py, Line: 227 in run()
    └─ File: /home/devel/tenv/lib/python3.11/site-packages/rdetoolkit/modeproc.py, Line: 289 in invoice_mode_process()
        └─ File: /home/devel/tenv/lib/python3.11/site-packages/rdetoolkit/validation.py, Line: 77 in metadata_validate()
            └─> L77: raise FileNotFoundError(emsg) 🔥

Exception Type: FileNotFoundError
Error: The schema and path do not exist: metadata.json
```

**Comment by sonoh5n** [comment]
initで生成できるファイルを以下のように変更し、テスト用の構造化処理スクリプトを作成するように変更した。

modules/modules.pyでダミー用の`metadata.json`を生成、デフォルトでエラーが発生しないように回避。

### main.py

```python
# The following script is a template for the source code.

import rdetoolkit
from modules.modules import dataset

rdetoolkit.workflows.run(custom_dataset_function=dataset)
```

### container/modules/modules.py

```python
import json
from rdetoolkit.models.rde2types import RdeInputDirPaths, RdeOutputResourcePath
from rdetoolkit.exceptions import catch_exception_with_message


def load_data_from_file(file_path):
    """Load data from a file.

    Args:
    - file_path : The path to the file to be loaded.

    Returns:
    - data: The loaded data.
    """
    # Return dummy data (implement the file loading logic here)
    data = {"date": ["2024-01-01", "2024-01-02", "2024-01-03"], "value": [100, 200, 150]}
    # Replace with actual data loading logic
    return data


def plot_graph(data):
    """Plot a graph from the given data.

    Args:
    - data: The data to be plotted.

    Returns:
    - graph: The generated graph.
    """
    # Implement the graph plotting logic here
    ...


def save_metadata(resource_paths):
    """Save metadata to a file.

    Args:
    - resource_paths: The resource paths to save the metadata.
    """
    with open(resource_paths.meta.joinpath("metadata.json"), mode="w", encoding="utf-8") as f:
        json.dump({"constant": {}, "variable": []}, f, ensure_ascii=False, indent=2)


@catch_exception_with_message(error_message="Custom error message", error_code=100, verbose=True)
def dataset(srcpaths: RdeInputDirPaths, resource_paths: RdeOutputResourcePath):
    """This function is a custom structured processing script.
    Customize and define the structured processing for each user. Typically, the following processing is executed:
    - Reading input files
    - Extracting metadata
    - Plotting graphs
    Also, error_message="Custom error message" allows you to define the message output on RDE. Feel free to change it.

    Args:
        srcpaths (RdeInputDirPaths): Paths to files generated by the file system registered in RDE
        resource_paths (RdeOutputResourcePath): Paths to the loaded input files and output directories
    """
    # Get input file path
    # ex: data_path = resource_paths.rawfiles[0].joinpath("data.csv")
    data_path = "data.csv"

    # 1. Read input data
    data = load_data_from_file(data_path)

    # 2. Plot graph and save image
    plot_graph(data)

    # 3. Save metadata
    save_metadata(resource_paths)

```
