### ISSUE TITLE
バリデーション機能のエラー表示を改善する

### ISSUE THREAD

**Issue by sonoh5n** [nims-dpfc/rdetoolkit#14]
## 内容

`invoice.schema.json`のバリデーションのエラー時の結果が見づらいため、エラー表示を改善する。

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/rdetoolkit/validation.py", line 167, in pre_validate
    InvoiceSchemaJson(**data)
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 193, in init__
    self.pydantic_validator.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for InvoiceSchemaJson
properties.custom.required
  Field required [type=missing, input_value={'type': 'object', 'label...e'}, 'type': 'string'}}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/rdetoolkit/workflows.py", line 200, in run
    invoice_mode_process(srcpaths, rdeoutput_resource, custom_dataset_function, config=config)
  File "/usr/local/lib/python3.11/site-packages/rdetoolkit/modeproc.py", line 293, in invoice_mode_process
    invoice_validate(resource_paths.invoice.joinpath("invoice.json"), schema_path)
  File "/usr/local/lib/python3.11/site-packages/rdetoolkit/validation.py", line 261, in invoice_validate
    validator = InvoiceValidator(schema)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rdetoolkit/validation.py", line 92, in init__
    self.schema = self.pre_validate()
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rdetoolkit/validation.py", line 170, in pre_validate
    raise InvoiceSchemaValidationError(emsg) from validation_error
rdetoolkit.exceptions.InvoiceSchemaValidationError: Error in schema validation
root@bda61f93c36b:/app2# 
```

**Comment by sonoh5n** [comment]
## invoice.schema.json/invoice.jsonのバリデーションエラー表示例

```bash
Error: Validation Errors in invoice.schema.json. Please correct the following fields
1. Field: properties.custom.type
   Type: literal_error
   Context: Input should be 'object'
2. Field: properties.custom.properties.common_data_type.type
   Type: literal_error
   Context: Input should be 'boolean', 'integer', 'number' or 'string'
```

**Comment by sonoh5n** [comment]
Pydanticのデフォルトのスタックトレースを少し修正し、どこでエラーが発生したかを明示的に変更。変更が完了したため、closed

**Comment by hi-nagao** [comment]
ご対応ありがとうございます。
