### ISSUE TITLE
invoice.jsonのsample、customが、必須指定していないのに、"必須だけど空"エラー

### ISSUE THREAD

**Issue by henami** [nims-dpfc/rdetoolkit#17]
とりあえずinvoice.jsonのスキーマチェックを避ける目的で
```
(venv) $ vi data/tasksupport/invoice.schema.json
：
  "required": [
  ],
：
```
にして、構造化処理プログラムを作成して実行したところ
```
(venv) $ python main.py
Hello RDE!
Traceback (most recent call last):
  File "/home/devel/venv/lib/python3.12/site-packages/rdetoolkit/validation.py", line 167, in __pre_validate
    InvoiceSchemaJson(**data)
  File "/home/devel/venv/lib/python3.12/site-packages/pydantic/main.py", line 192, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for InvoiceSchemaJson
  Value error, custom is required but is None [type=value_error, input_value={'$schema': 'https://json...b-5a26f8a74166'}}}]}}}}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/value_error
：
```
となりました。

ソース確認したところ
```
(venv) $ vi /home/devel/venv/lib/python3.12/site-packages/rdetoolkit/models/invoice_schema.py
：
class InvoiceSchemaJson(BaseModel):
：
    @model_validator(mode="after")
    def __check_required_fields(self):
        if self.required is None:
            return self
        if "custom" in self.required and self.properties.custom is None:
            raise ValueError("custom is required but is None")
        elif "sample" in self.required and self.properties.sample is None:
            raise ValueError("sample is required but is None")
        return self

    @model_validator(mode="after")
    def __check_custom_fields(self):
        if not self.properties.custom:
            return self
        if "custom" not in self.required:
            raise ValueError("custom is required but is None")
        return self

    @model_validator(mode="after")
    def __check_smaple_field(self):
        if not self.properties.sample:
            return self
        if "sample" not in self.required:
            raise ValueError("sample is required but is None")
        return self
```
あたりが関係していそうなことは分かりました。

__check_custom_fields()と__check_smaple_field()ですが、"requiredに入っていなかったら"というif文なのに、そのエラーメッセージが"custom is required but is None"/"sample is required but is None"になっています。

1) この"if "sample" not in self.required:" の"not"が不要でしょうか?

2) 仮に不要だとしたら、__check_required_fields()内で実施しているチェックとダブる気がします。__check_required_fields()内で、実際に空かどうかのチェックは不要のような気がします。

3) self.requiredの値をみましたが、`[]`(→空の配列)でした。空の配列は"None"では無いと思いますが、ロジック的に問題ないでしょうか?

**Comment by sonoh5n** [comment]
@henami ご指摘ありがとうございます。

`__check_required_fields(self)`は、invoice.schema.jsonのrequiredフィールドのカスタムバリデーションです。requiredの要件として _固有情報を入力させる場合は"custom"を含める。試料情報を入力させる場合は"sample"を含める。_ とあるため、

- requiredに、`custom`と`sample`記載なし -> チェックしない
- `properties`以下に`custom`の記載されてないにもかかわらず、`custom`がrequiredに書かれている条件(記載し忘れなど)はエラーにしています。(sampleも同様です。)

`__check_custom_fields(self)`は、invoice.schema.jsonの`properties.custom`フィールドのカスタムバリデーションです。ここは、`required`に`custom`が書かれていないにもかかわらず、`properties.custom`があるものをバリデーションエラーにしています。(`__check_sample_fields(self)`も同様です。)

_固有情報を入力させる場合は"custom"を含める。試料情報を入力させる場合は"sample"を含める。_  のcustomとsampleは、`invoice.json`のフィールドを指しているのかもしれませんが、`invoice.schema.json`がUIのバリデーションファイルである以上、どちらかが書かれていないケースはエラーにする想定で上記の処理を記載しました。

エラーメッセージや判定処理等の改善は、よろしくないので対応します。

> 本来であれば、`__check_custom_fields(self)`と`__check_sample_fields(self)`は、Propertiesクラスに実装するべきですが、pydanticのモデルバリデーターの仕組みを完全にわかっていないため、ここに定義しています。

**Comment by henami** [comment]
@sonoh5n 確認ありがとうございます。仕様の確認も必要ですね。

で、ほぼ繰り返しになりますが、その仕様には
```
No 項目(JSONポインタ表現) バリュー型 フォーマット 必須 固定値 値の例 説明 仕様補足名
：
6 /required array - - - ["custom","sample"] 固有情報を入力させる場合は"custom"を含める。試料情報を入力させる場合は"sample"を含める。
：
```
ってことですね。なるほど。

>requiredに、customとsample記載なし -> チェックしない

当然ですね。

> properties以下にcustomの記載されてないにもかかわらず、customがrequiredに書かれている条件(記載し忘れなど)はエラーにしています。(sampleも同様です。)

これも理解できます。当然です。

> ここは、requiredにcustomが書かれていないにもかかわらず、properties.customがあるものをバリデーションエラーにしています。

およよ。そうなの?

>どちらかが書かれていないケースはエラーにする想定で上記の処理を記載しました。

つまりrequiredが`[]`(空のリスト)になることは、あり得ないっていうことなのかしら?

**Comment by sonoh5n** [comment]
> requiredが[](空のリスト)になることは、あり得ない

空になるケースはあります。空になるケースは、`/properties`を空になる場合です。

invoice.schema.jsonの`/required`は、`固有情報を入力させる場合は"custom"を含める。試料情報を入力させる場合は"sample"を含める。`という前提であるため、requiredが`[]`にするのであれば、`/properties`を空にしてください。

もし、`/properties`以下に、固有情報`custom`, 試料情報`sample`を入力している場合、`custom`, `sample`を適宜`/required`に入力してください。
