### ISSUE TITLE
エクセルインボイスモードで、Excelファイルに空のシートがあるとエラーになる

### ISSUE THREAD

**Issue by henami** [nims-dpfc/rdetoolkit#34]
表記の件ですが、Excelシートに空のシート(いずれにセルにもなにも入っていないシート)が存在している場合、以下の様にエラーとなります。
空のシートがある場合でも、無視するようにできないでしょうか?

```bash
(venv) $ python main.py 
Traceback (most recent call last):
  File "/home/devel/venv/lib/python3.12/site-packages/pandas/core/indexes/range.py", line 1018, in __getitem__
    return self._range[new_key]
           ~~~~~~~~~~~^^^^^^^^^
IndexError: range object index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/devel/venv/lib/python3.12/site-packages/rdetoolkit/workflows.py", line 212, in run
    raw_files_group, excel_invoice_files = check_files(srcpaths, mode=__config.extended_mode)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/devel/venv/lib/python3.12/site-packages/rdetoolkit/workflows.py", line 78, in check_files
    rawfiles, excelinvoice = input_checker.parse(srcpaths.inputdata)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/devel/venv/lib/python3.12/site-packages/rdetoolkit/impl/input_controller.py", line 99, in parse
    rawfiles = self._get_rawfiles(zipfiles[0], excel_invoice_files[0]) if zipfiles else self._get_rawfiles(None, excel_invoice_files[0])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/devel/venv/lib/python3.12/site-packages/rdetoolkit/impl/input_controller.py", line 110, in _get_rawfiles
    df_excel_invoice, _, _ = read_excelinvoice(excel_invoice_file)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/devel/venv/lib/python3.12/site-packages/rdetoolkit/invoicefile.py", line 45, in read_excelinvoice
    if df.iat[0, 0] == "invoiceList_format_id":
       ~~~~~~^^^^^^
  File "/home/devel/venv/lib/python3.12/site-packages/pandas/core/indexing.py", line 2527, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/devel/venv/lib/python3.12/site-packages/pandas/core/frame.py", line 4211, in _get_value
    series = self._ixs(col, axis=1)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/devel/venv/lib/python3.12/site-packages/pandas/core/frame.py", line 4008, in _ixs
    label = self.columns[i]
            ~~~~~~~~~~~~^^^
  File "/home/devel/venv/lib/python3.12/site-packages/pandas/core/indexes/range.py", line 1020, in __getitem__
    raise IndexError(
IndexError: index 0 is out of bounds for axis 0 with size 0


============================================================
Custom Traceback (simplified and more readable):
============================================================

Traceback (simplified message):
Call Path:
   File: /home/devel/venv/lib/python3.12/site-packages/rdetoolkit/workflows.py, Line: 212 in run()
    └─ File: /home/devel/venv/lib/python3.12/site-packages/rdetoolkit/workflows.py, Line: 78 in check_files()
        └─ File: /home/devel/venv/lib/python3.12/site-packages/rdetoolkit/impl/input_controller.py, Line: 99 in parse()
            └─ File: /home/devel/venv/lib/python3.12/site-packages/rdetoolkit/impl/input_controller.py, Line: 110 in _get_rawfiles()
                └─ File: /home/devel/venv/lib/python3.12/site-packages/rdetoolkit/invoicefile.py, Line: 45 in read_excelinvoice()
                    └─ File: /home/devel/venv/lib/python3.12/site-packages/pandas/core/indexing.py, Line: 2527 in __getitem__()
                        └─ File: /home/devel/venv/lib/python3.12/site-packages/pandas/core/frame.py, Line: 4211 in _get_value()
                            └─ File: /home/devel/venv/lib/python3.12/site-packages/pandas/core/frame.py, Line: 4008 in _ixs()
                                └─ File: /home/devel/venv/lib/python3.12/site-packages/pandas/core/indexes/range.py, Line: 1020 in __getitem__()
                                    └─> L1020: raise IndexError( 🔥

Exception Type: IndexError
Error: index 0 is out of bounds for axis 0 with size 0
```

**Comment by sonoh5n** [comment]
本件は、 #35 がマージされたらissueをクローズします。
